/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import apiVideoUploader from "@api.video/strapi-uploader-plugin/strapi-admin";
import githubProjects from "@artcoded/strapi-plugin-github-projects/strapi-admin";
import contentVersioning from "@notum-cz/strapi-plugin-content-versioning/strapi-admin";
import dragDropContentTypes from "@retikolo/drag-drop-content-types/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiChatgpt from "strapi-chatgpt/strapi-admin";
import strapiPluginCkeditor5 from "strapi-plugin-ckeditor5/strapi-admin";
import emailDesigner from "strapi-plugin-email-designer/strapi-admin";
import oembed from "strapi-plugin-oembed/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "api-video-uploader": apiVideoUploader,
    "github-projects": githubProjects,
    "content-versioning": contentVersioning,
    "drag-drop-content-types": dragDropContentTypes,
    graphql: graphql,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "strapi-chatgpt": strapiChatgpt,
    "strapi-plugin-ckeditor5": strapiPluginCkeditor5,
    "email-designer": emailDesigner,
    oembed: oembed,
  },
});
